#! /bin/bash

version="1.0"

#root init vasctl
if [ "$EUID" != "0" ]; then 
    echo "[INFO] Please run as root"
    exit
fi

#Parm init
if [ "$1" = "" ] || [ "$1" = "-h" ]; then
  echo "Welcome to vasctl $version !"
  echo ""
  echo "Usage:"
  echo ""
  echo "Installing OpenVAS to your OS:"
  echo "Debian: # vasctl install debian"
  echo "Arch:   # vasctl install arch"
  echo ""
  echo "First installation"
  echo "$ get-waterfox download >>> Download the current Waterfox Tarball >>> -d"
  echo "# get-waterfox install >>> Install the Waterfox Tarball & create all links etc >>> -i"
  echo ""
  echo "General commands"
  echo "# get-waterfox update >>> Update Waterfox >>> -u"
  echo "$ get-waterfox cleanup >>> Delete old waterfox tarball >>> -C"
  echo "$ get-waterfox checkupdate >>> Shows if a Waterfox update is available >>> -c"
  echo "$ get-waterfox version >>> Print version of get-waterfox >>> -v"
  echo ""
  echo "Remove Waterfox"
  echo "# get-waterfox remove >>> Remove Waterfox complete >>> -r"
  echo ""
  echo "Use '-h' to show this help"
  echo "Please run the commands this way: init; download; install"
  exit
fi

#Install
if [ "$1" = "install" ] || [ "$1" = "-i" ]; then
  echo "Installing vasctl $version for Debian!"
  echo "[INFO] Updating apt ..."
  apt update
  echo "[INFO] Installing packages ..."
  apt install openvas -y
  exit
fi

echo "" > /etc/redis.vasctl.bk
echo $(cat /etc/redis.conf) >> /etc/redis.vasctl.bk
echo "unixsocket /var/lib/redis/redis.sock" > /etc/redis.conf
echo "unixsocketperm 700" >> /etc/redis.conf
echo "port 0" >> /etc/redis.conf
echo "timeout 0" >> /etc/redis.conf
echo "databases 128" >> /etc/redis.conf
echo "kb_location = /var/lib/redis/redis.sock" > /etc/openvas/openvassd.conf
systemctl start redis.service
openvas-manage-certs -a
greenbone-nvt-sync
greenbone-scapdata-sync
greenbone-certdata-sync
systemctl start openvas-scanner.service
openvasmd --rebuild --progress
echo "[INFO] Setting up user stuff ..."
openvasmd --create-user=admin --role=Admin
echo "[INFO] Generating random password for session ..."
randompass="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')"
openvasmd --user=admin --new-password=$randompass
systemctl start openvasmd.service
openvasmd -p 9390 -a 127.0.0.1
gsad -f --listen=127.0.0.1 --mlisten=127.0.0.1 --mport=9390
